version: '3.8'

services:
  db:
    container_name: db
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Netmarket123!
      - MSSQL_TCP_PORT=1433
    ports:
      - "1400:1433"
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=NetMarket;User=sa;Password=Netmarket123!
    ports:
      - "5005:5005"
    depends_on:
      - db
    restart: always
  client:
    container_name: client
    build:
      context: ./src/Client
      dockerfile: ./Dockerfile
    ports:
      - "5006:80"
    depends_on:
      - api
    restart: always